{% set name = "galgebra" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygae/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1ef1291208071b5c074e3e0056e88d03b48281f9eecfa7fa177f53964ed24184

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip   
  run:
    - python
    - sympy

test:
  imports:
    - galgebra

about:
  home: http://galgebra.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Symbolic Geometric Algebra/Calculus package for SymPy.'

  description: |
    Symbolic Geometric Algebra/Calculus package for SymPy. BSD License.
  doc_url: http://galgebra.readthedocs.io
  dev_url: https://github.com/pygae/galgebra

extra:
  recipe-maintainers:
    - utensil
    - hugohadfield
