{% set name = "galgebra" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pygae/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6958b2b23d2343c5f7273e00f56cb466f10350c6ee903e56292cd35b7af90ba4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sympy

test:
  requires:
    - python {{ python_min }}
  imports:
    - galgebra

about:
  home: http://galgebra.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Symbolic Geometric Algebra/Calculus package for SymPy.

  description: |
    Symbolic Geometric Algebra/Calculus package for SymPy. BSD License.
  doc_url: http://galgebra.readthedocs.io
  dev_url: https://github.com/pygae/galgebra

extra:
  recipe-maintainers:
    - utensil
    - hugohadfield
