travis:
  secure:
    BINSTAR_TOKEN: Ek7lRp5qpShXbgloELMzVByrjftqWW5RGn0A0suy1WWUK9tj5NONYcOFcmHkBfuPQK9fZms7LIJpl14I5JbDQ/XnsihxXZ5Uu3AZg8eMUnkUyZgbSpYDtuqLYUshyjccWMbwsBTLjaaRAwJiFTxDoegGHN8kx35YrPE8VM2v3nBiw7f6Ze6koi3OiUn1TWCdAbdd4PmD4AsjtXPfWdHJDkQiybfMIB3Z73M1us6ll44OUFCjRobLBVUPR+fpHMPxZySiFM0A6jTGdVOo7KvPwSvD/ObYOiJv0VJ6SlSlfg4tZOrKPYPCcmGb8Y3cGvFeCH2rUI0g+TIBgab0b2D4Pzouwe+eL/WMoqXZK219UZ5EtRJuipl3u3D4LGLlr0+/d3Gtr3CAi/ITFTpGpy0keSdGJRI6ju6+QW1srow2FGmxatDzkOk2BpQtigRfNEIi/bIf52r7RbX2s0oVTrFwMMQJZKCh4GUpe/gBn5a8ZLM194wnJDaYw1ZpilMqLSIUAEbwpxpqu40RJyc92/EdAREDCWgCIiydY7wBRNKOE/OYdjJt68wyLfxTU8xqENnmjzG8stuoEW49KZJkXme2vdCDWWUEqtZm33ihBfQT+zTV9xJUdaoulSmwFWrhVp3WQAii/bwx3nXnlaoA2rMuuSYJrGgbF554bP16jMHDynA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
